"""Secrets management for the Autonima web UI."""

from __future__ import annotations

from pathlib import Path
from typing import Dict

SECRETS_KEYS = [
    "OPENAI_API_KEY",
    "OPENAI_API_GATEWAY",
    "PUBGET_API_KEY",
    "NCBI_EMAIL",
]


class SecretsManager:
    """Manage keys stored in ~/.autonima.env."""

    def __init__(self, env_path: Path | None = None):
        self.env_path = env_path or (Path.home() / ".autonima.env")

    def _parse(self, text: str) -> Dict[str, str]:
        values: Dict[str, str] = {}
        for line in text.splitlines():
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue
            if "=" not in stripped:
                continue
            key, value = stripped.split("=", 1)
            values[key.strip()] = value.strip()
        return values

    def load(self) -> Dict[str, str]:
        if not self.env_path.exists():
            return {}
        content = self.env_path.read_text(encoding="utf-8")
        return self._parse(content)

    def load_masked(self) -> Dict[str, str]:
        secrets = self.load()
        masked: Dict[str, str] = {}
        for key in SECRETS_KEYS:
            value = secrets.get(key, "")
            if not value:
                masked[key] = ""
            elif len(value) <= 6:
                masked[key] = "*" * len(value)
            else:
                masked[key] = f"{value[:3]}{'*' * max(3, len(value) - 6)}{value[-3:]}"
        return masked

    def save(self, updates: Dict[str, str]) -> Dict[str, str]:
        current = self.load()
        for key in SECRETS_KEYS:
            if key not in updates:
                continue
            value = (updates.get(key) or "").strip()
            if value:
                current[key] = value
            elif key in current:
                del current[key]

        lines = [
            "# Autonima UI secrets",
            "# Generated by `autonima ui`",
            "",
        ]
        for key in SECRETS_KEYS:
            value = current.get(key)
            if value:
                lines.append(f"{key}={value}")

        self.env_path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
        try:
            self.env_path.chmod(0o600)
        except OSError:
            # Best-effort permissions for cross-platform compatibility.
            pass

        return self.load()
